eureka:
  instance:
    hostname: 13.126.8.44
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://13.126.8.44:9999/eureka/
    
