spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/companydb
    username: postgres
    password: 12345678
 
  boot:
    admin:
      client:
        url: http://localhost:1111
  jpa:
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
