spring:
  cloud:
    gateway:
      routes:
        - id: company-service
          uri: lb://company-service  # URL of the company service
          predicates:
            - Path=/api/v1/companies/**  # route for company-service
        - id: employee-service
          uri: lb://employee-service  # URL of the employee service
          predicates:
            - Path=/api/v1/employees/**  # route for employee-service
