spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: postgres
    password: 12345678

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



